frontend:
	@echo Installing Frontend
catalogue:
	@echo Installing catalogue
user:
	@echo Installing user
cart:
	@echo Installing cart
shipping:
	@echo Installing shipping
payment:
	@echo Installing payment
mongodb:
	@echo Installing mongodb
redis:
	@echo Installing redis
rbbitmq:
	@echo Installing rbbitmq
mysql:
	@echo Installing mysql

