help: ## Print this message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend: 			## Install Frontend Component
	@echo Installing Frontend
catalogue: 			## Install catalogue Component
	@echo Installing catalogue
user: 				## Install user Component
	@echo Installing user
cart: 				## Install cart Component
	@echo Installing cart
shipping: 			## Install shipping Component 
	@echo Installing shipping
payment:  			## Install payment Component
	@echo Installing payment
mongodb:  			## Install mongodb Component
	@echo Installing mongodb
redis:  			## Install redis Component
	@echo Installing redis
rbbitmq: 			## Install rbbitmq Component
	@echo Installing rbbitmq
mysql:				## Install mysql Component
	@echo Installing mysql

